# -*- coding: utf-8 -*-
"""JogodaVelha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFIF1uSWY-muxwaKKQ0c-ObUfUMgNhs2
"""

def imprimir_tabuleiro(tabuleiro):
    for linha in tabuleiro:
        print(" | ".join(linha))
        print("-" * 9)

def verificar_vitoria(tabuleiro, jogador):
    # Verifica vitória nas linhas, colunas e diagonais
    for i in range(3):
        if all(tabuleiro[i][j] == jogador for j in range(3)) or all(tabuleiro[j][i] == jogador for j in range(3)):
            return True
    if all(tabuleiro[i][i] == jogador for i in range(3)) or all(tabuleiro[i][2 - i] == jogador for i in range(3)):
        return True
    return False

def jogar_jogo_da_velha():
    tabuleiro = [[" " for _ in range(3)] for _ in range(3)]
    jogadores = ["X", "O"]
    jogador_atual = 0

    while True:
        imprimir_tabuleiro(tabuleiro)
        jogador = jogadores[jogador_atual]
        print(f"Vez do Jogador {jogador}")

        linha = int(input("Digite a linha (0,  1, 2): "))
        coluna = int(input("Digite a coluna (0, 1, 2): "))

        if tabuleiro[linha][coluna] == " ":
            tabuleiro[linha][coluna] = jogador
            if verificar_vitoria(tabuleiro, jogador):
                imprimir_tabuleiro(tabuleiro)
                print(f"Jogador {jogador} venceu!")
                break
            elif all(tabuleiro[i][j] != " " for i in range(3) for j in range(3)):
                imprimir_tabuleiro(tabuleiro)
                print("Empate!")
                break
            jogador_atual = 1 - jogador_atual  # Alternar entre os jogadores
        else:
            print("Essa posição já está ocupada. Escolha outra.")

if __name__ == "__main__":
    jogar_jogo_da_velha()